<?xml version="1.0"?>
<package format="3">
  <name>robot_control</name>
  <version>1.0.0</version>
  <description>ROS2 package for ST3215 6-axis robot manipulator control</description>
  <maintainer email="lyachov@example.com">Alexandr Lyachov</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>trajectory_msgs</depend>

  <!-- rosbag2 -->
  <depend>rosbag2_py</depend>
  <depend>rosbag2</depend>
  <depend>rosbag2_storage</depend>
  <depend>rosbag2_storage_default_plugins</depend>

  <!-- ros2_control -->
  <depend>ros2_control</depend>
  <depend>ros2_controllers</depend>
  <depend>controller_manager</depend>
  <depend>joint_trajectory_controller</depend>
  <depend>joint_state_broadcaster</depend>
  <depend>control_msgs</depend>
  <depend>robot_state_publisher</depend>
  <depend>xacro</depend>

  <buildtool_depend>ament_python</buildtool_depend>
  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
