arm:
  planner_configs:
    - RRTConnect
    - RRTstar
    - BKPIECE
  RRTConnect:
    type: geometric::RRTConnect
  RRTstar:
    type: geometric::RRTstar
  BKPIECE:
    type: geometric::BKPIECE
  projection_evaluator: joints(joint_0,joint_1)
  longest_valid_segment_fraction: 0.005
